### ISSUE TITLE
line 23，params = '&to=de&to=it' the first to should be from

### ISSUE THREAD

**Issue by coco-1998-2** [MicrosoftTranslator/Text-Translation-API-V3-Python#10]
Translate.py file: line 23，params = '&to=de&to=it' the first to should be from, '&from=de&to=it' 
![image](https://user-images.githubusercontent.com/41716753/67619239-a3638000-f82b-11e9-8723-ce4dd1799dba.png)

**Comment by shawn-jung** [comment]
In a way, I agree with the issue above. The API does detect the language if 'from' is not presented, but it would be better to define params as `'&from=en&to=de&to=it'` to show the API is capable of showing multiple responses in multiple languages, and one can set the source language.

**Comment by chriswendt1** [comment]
Right. The sample is meant to show that you may specify multiple target languages and may omit the from= parameter.
