### ISSUE TITLE
where can I find "endpoint" and "subscription_key" from my azure dashboard?

### ISSUE THREAD

**Issue by zzks** [MicrosoftTranslator/Text-Translation-API-V3-Python#13]
I can find "key1" "key2" and "endpoint" from my dashboard.
and endpoint looks like this: https://eng2jap.cognitiveservices.azure.com/sts/v1.0/issuetoken
I got 404 no found when using key1 and this endpoint by the python code.
please give me some advice. Thanks!

**Comment by Godric877** [comment]
Hi! Did you find the solution to the 404 error problem yet? Can you please guide me towards the solution?
