### ISSUE TITLE
Count of translated characters

### ISSUE THREAD

**Issue by swaticolab** [MicrosoftTranslator/Text-Translation-API-V3-Python#15]
There is a limit of 12M characters per month to the F0 pricing tier. I wanted to clarify what if I have given let's say 10M characters to the API, out of which only 1M characters need translation.
For eg. I want to have all characters in English, but only 1M characters are non-English, which means effectively the API is working on 1M characters only.
So will I be charged for complete 10M characters, or only 1M characters?

**Comment by chriswendt1** [comment]
The API counts all characters passed to it, whether it results in a translation or not.
