### ISSUE TITLE
does not give output when translating between languages of 2 scripts

### ISSUE THREAD

**Issue by vaishnavijha** [MicrosoftTranslator/Text-Translation-API-V3-Python#16]
when i have deployed the python code via spawn with my node js to build my api i am not getting the outpt if i translate a text from english to hindi

**Comment by shushill** [comment]
Follow this tutorial, I guess it may help you...
https://docs.microsoft.com/en-us/azure/cognitive-services/Translator/quickstart-translate?pivots=programming-language-python

**Comment by vaishnavijha** [comment]
thank youSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Sushil Verma <notifications@github.com> Date: 28/05/2020  02:54  (GMT+05:30) To: MicrosoftTranslator/Text-Translation-API-V3-Python <Text-Translation-API-V3-Python@noreply.github.com> Cc: vaishnavi jha <vaishnavi.jha.poorna@gmail.com>, Author <author@noreply.github.com> Subject: Re: [MicrosoftTranslator/Text-Translation-API-V3-Python] does not give output when translating between languages of 2 scripts (#16) 
Follow this tutorial, I guess it may help you...
https://docs.microsoft.com/en-us/azure/cognitive-services/Translator/quickstart-translate?pivots=programming-language-python

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftTranslator/Text-Translation-API-V3-Python/issues/16#issuecomment-634948729",
"url": "https://github.com/MicrosoftTranslator/Text-Translation-API-V3-Python/issues/16#issuecomment-634948729",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by chriswendt1** [comment]
I believe this is the same as issue #20 and fixed now.
