### ISSUE TITLE
About the Translate.py sample 

### ISSUE THREAD

**Issue by dalgrnd** [MicrosoftTranslator/Text-Translation-API-V3-Python#17]
Hello , 
I couldn't run the script Translate.py until I forced the parameter 'Ocp-Apim-Subscription-Region' in the header to the region of my subscription , to me 'francecentral' . 
Otherwise great sample.
Thank you .

**Comment by ghernandez-cei** [comment]
+1 to this. Was having issues getting mine to work and I was missing this parameter from the header as well. Thank you for raising!

**Comment by chriswendt1** [comment]
Thanks for the report. Fixed now in the samples.
