### ISSUE TITLE
Translate.py contains two "to" parameters in the params object

### ISSUE THREAD

**Issue by luisesanmartin** [MicrosoftTranslator/Text-Translation-API-V3-Python#18]
I apologize in case I'm wrong, I'm very new to the Azure translator Python API. My sense is that in this part:
```
params = '&to=de&to=it'
```
one of the `to` parameters should actually be a language to translate from

**Comment by chriswendt1** [comment]
By design: This is to demonstrate that you can translate to multiple languages at once. 
You may add a from= parameter as well. Omitting from like in the example will auto-detect the source language.
