### ISSUE TITLE
Result output broken in translate.py

### ISSUE THREAD

**Issue by yananet** [MicrosoftTranslator/Text-Translation-API-V3-Python#20]
https://github.com/MicrosoftTranslator/Text-Translation-API-V3-Python/blob/dc2abc16839c6615b45aa54358ae75005ef1f91a/Translate.py#L41

If the output is not English, `ensure_ascii=False` should be provided in `json.dumps` as below,
otherwise, the result could be broken.

`print(json.dumps(response, sort_keys=True, indent=4, ensure_ascii=False, separators=(',', ': '))) `

**Comment by yananet** [comment]
the sample here already includes `ensure=ascii=False`.
https://docs.microsoft.com/en-us/azure/cognitive-services/translator/quickstart-translator?tabs=python

**Comment by chriswendt1** [comment]
Thanks for the report. 
Fixed now.
