### ISSUE TITLE
Ocp-Apim-Subscription-Region is missing from the headers

### ISSUE THREAD

**Issue by balinttahi** [MicrosoftTranslator/Text-Translation-API-V3-Python#25]
I was not able to make the Translate.py work, because all I got back from the API was: 

```
{
    "error": {
        "code": 401000,
        "message": "The request is not authorized because credentials are missing or invalid."
    }
}
```

I was investigating the documentation and it seems, that the **Ocp-Apim-Subscription-Region** header is required for the authentication.

**Comment by chriswendt1** [comment]
Thanks a lot for the report. Fixed now. Let me know if you find other issues.
