### ISSUE TITLE
"message": "Resource not found"

### ISSUE THREAD

**Issue by sowinski** [MicrosoftTranslator/Text-Translation-API-V3-Python#9]
Examples not working for me. Can anyone confirm that?

I got always this error?
```
{
    "error": {
        "code": "404",
        "message": "Resource not found"
    }
}

```

**Comment by shawn-jung** [comment]
You will want to check the endpoint URL. Especially, if you were using the cognitive services issue token end-point in Quick Start screen (such as  https://XXX.cognitiveservices.azure.com/sts/v1.0/issuetoken ), please try the API end point. https://api.cognitive.microsofttranslator.com

**Comment by chriswendt1** [comment]
Copy the endpoint exactly as listed in the Translator resource on Azure " Keys and Endpoint" page. 
https://portal.azure.com.
